---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: konvoyconfig
  namespace: kubeaddons
  labels:
    kubaddons.mesosphere.io/name: konvoyconfig
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.0.4-4"
    appversion.kubeaddons.mesosphere.io/konvoyconfig: "0.0.4"
    values.chart.helm.kubeaddons.mesosphere.io/konvoyconfig: "https://raw.githubusercontent.com/mesosphere/charts/173f2200647defaf67e96b32cfdbb5b6932f1fa5/staging/konvoyconfig/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.6
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: vsphere
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: konvoyconfig
    repo: https://mesosphere.github.io/charts/staging
    version: 0.0.5
    values: |
      ---
      config:
        # clusterHostname should be a FQDN that resolves to the cluster's ingress VIP.
        # This value will be used to generate certificates for traefik and configure dex.
        clusterHostname: ""
